import requests

headers = {'Content-Type': 'application/json'}

r = requests.post('http://sql2regex.herokuapp.com/api/settingsoptions', headers=headers)
print(r.text)

# ["COLUMNNAMESPELLING","KEYWORDSPELLING","TABLENAMESPELLING","COLUMNNAMEORDER","TABLENAMEORDER",
# "INDEXCOLUMNNAMEORDER","INDEXCOLUMNNAMESPELLING","DATESYNONYMS","DATETIMESYNONYMS","TIMESYNONYMS",
# "AGGREGATEFUNCTIONLANG","DATATYPESYNONYMS","GROUPBYELEMENTORDER","INSERTINTOVALUESORDER",
# "OTHERSYNONYMS","DEFAULT"]